### ISSUE TITLE
Allow CLA check from commits sha

### ISSUE THREAD

**Issue by leobalter** [jquery/jquery-license#26]
Today I fixed the commit author info on jquery/qunit#751 to make it pass on the CLA check. The commit wasn't originally mine and I figured out the only way to double check the CLA information was creating another PR.

I would be great to have anything to check the CLA through a commit SHA, even it's on a temp branch on the github project's repo. 

from IRC, @scottgonzalez talked about a binary, which would also solve this problem:

```
$ jquery-audit-commit SHA
```

**Comment by scottgonzalez** [comment]
To fill in the missing information:

This would run from inside the repo directory, which means we're using very different logic for some parts (no fetching, not using the `repos` directory, etc.).

SHA would be probably be a committish, not just a single SHA. To check a single SHA we'd probably want a flag (perhaps `-c SHA`) to avoid needing to do `SHA^...` for a single commit.

**Comment by jzaefferer** [comment]
This could be achieved by cloning this repo, setting up a `config.json` with a personal GitHub API token and `owner: "jquery"`, than running `bin/audit-pr [repo] [pr]`. Then the developers GitHub account would update the labels on the PR, instead of #jquerybot. If that sounds reasonable, I'll do a PR against the README where I document this in a bit more detail, then @leobalter or @rxaviers can try it.

**Comment by arschmitz** [comment]
:+1: this seems like a non common use case so that seems good enough to me.
