### ISSUE TITLE
Email and Name checks should not be case sensitive

### ISSUE THREAD

**Issue by kborchers** [jquery/jquery-license#47]
Email addresses still resolve no matter the case used and a person is still the same person if their name is in all caps or all lower case. This would also prevent false failures if someone accidentally capitalizes the first 2 letters in their name or something when typing.

**Comment by kborchers** [comment]
I would say no but we can ask @StevenAyr to chime in

**Comment by StevenAyr** [comment]
I don't think that there's any legal significance to the case of a name or email address, it's just about showing that someone agreed, intending to be legally bound.

**Comment by whyAmIseeay** [comment]
Execuse me, but are you sure about that, @StevenAyr? Emails are technically case sensitive (see RFC 2821), and I assume it's somewhat significant that it's the correct mail, right? People tend to believe emails are case insensitive but that's only because they (or their mail host) chose to do so, they, generally aren't really insensitive but just aliased.
